modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="furmutage"
version="0.0.1"
displayName="Furmutage"
credits="cool credits"
displayURL="" #Mod "page" if any
updateJSONURL="" #paste the json update checker url here
logoFile="logo.png"
authors="Cool dev names goes here"
description="cool description"

[[dependencies.furmutage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.furmutage]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.furmutage]]
    modId="changed"
    mandatory=true
    versionRange="[0.15.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.furmutage]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

